name: Test Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test_build:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Build and install
      run: |
        python -m pip install pytest
        pip install --verbose .